Add support for T2 Unlimited
tangerinedream/AWS_EC2_Scheduler pull request #24
Opened 2018-02-13 17:18 UTC by igordavid

PR is to add support for T2 Unlimited. 

If "-p" flag is defined, it will check if ".u" or ".U" is present in DynamoDB for TierScaling e.g.

"Small":"t2.small.u"
"Large":"t2.large.U"

... it will modify instance to T2.Unlimited.

If "-p" flag is defined and there is no ".u" or ".U" present in DynamoDB for Tierscaling, e.g.

"Small":"t2.small"
"Large":"t2.large"

... it will modify instance to T2.Standard

If no "-p" flag is used, it will start or stop instances as they are.

2018-02-14 04:19 UTC, tangerinedream reviewed
Some feedback:
1. t2unlimited() method should be called from with the scaleInstance() method, not from Orchestrator.  This abstracts the scaling knowledge to Worker.
2. We should not call ec2_client() from within t2Unlimited() method for several reasons, including you don't have the region.  In any event the ec2_client should already be available to the Worker as an instance variable (e.g. line 36 self.ec2Resource is defined)

3. line #190 is not checking dynamo but rather ec2 service.  This does not seem correct.  We should avoid API calls to check current values for instances.  Also, there's no need for API call at all, as the Worker has the instance already at construction time.  Just check the instance the Worker already has.

Let's review after updates.

2018-02-20 16:56 UTC, igordavid commented
Hi @tangerinedream ,

This should be now addressed. Please find comments:

1. Agreed, t2Unlimited() method has been moved to Worker

2. ec2_client have support for T2 Unlimited, ec2_resource don't, so we need to use ec2_client. Also, I think it maybe make sense to use connection string ec2_client in Worker.py and call it every time since it will perform network connectivity check towards AWS. If we use it in Orchestrator only, it may pass once and then fail on next Worker call (in case of some networking glitch or similar). What do you think?

2018-02-22 18:19 UTC, tangerinedream requested changes
There is an inefficiency in line #128 and #131 where they both call modifiedInstanceType.split().  We can fix that.  Please delete Worker line 128 and instead add the following after line 131:
131   modifiedInstanceTypeList = modifiedInstanceType.split('.')
132  targetInstanceFamily = modifiedInstanceTypeList [0]

2018-02-22 19:43 UTC, igordavid commented
Hi @tangerinedream ,

The changes has been made.

2018-02-22 19:45 UTC, tangerinedream approved these changes

2018-02-22 19:46 UTC, merged